language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
  - smac-group/stat297
  - jimhester/covr

after_success:
- Rscript -e 'library(covr);codecov()'

  
notifications:
    slack: smac-group:CqtVdLdbV1sCbO7c1gkVDpQE