init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    GITHUB_PAT:
      secure: SAjXHKPAFPipSOE/6giubmF50pmgGtSFxyhe88E7RDv+q4PucnkyRK7Rs+/a7Vo0

  matrix:
  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: patched
    GCC_PATH: mingw_32